news_sites:
    pagina12:
        url: http://www.pagina12.com.ar
    eltelegrafo:
        url: https://www.eltelegrafo.com/
    presidencia:
        url: https://www.presidencia.gub.uy/
    elpais:
        url: https://www.elpais.com/america/
    infobae:
        url: https://www.infobae.com/